### ISSUE TITLE
inverse mapping

### ISSUE THREAD

**Issue by marcrocasalonso** [lwileczek/isomap#1]
Dear IWILECZEK,

I have a question about the inverse transform of isomap. Do you have implemented any technique to return from the reduced space of ISOMAP to the input space?

Thank you in advance,
Regards 
Marc

**Comment by lwileczek** [comment]
I'm not familiar with an inverse function to this non-linear transformation. However, each point is still corresponding to the same sample before the features are just different.  Are you obtaining a collection of samples that have been transformed already without the original data?
